### PR TITLE
Overhaul the Options Menu and add custom keybinds

### PR DESCRIPTION
**Pull request by Zeexel**

### CODE REVIEW

**Comment by Zeexel** [comment]
Do it jiggle

**Comment by AyeTSG** [comment]
stop fucking bugging me

**Comment by Zeexel** [comment]
[https://media.discordapp.net/attachments/634549825303740447/849344670667898890/scp_173.png?width=712&height=702](hi)

**Comment by AyeTSG** [comment]
Please fix this issue with existing config files.

image

**Pull request closed without merging**
